# Site settings
title: Crazy Hams
description: Ham Radio guys with an extra of madness ツ
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://crazyhams.dev" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: crazyhams
user_description: Ham Radio Operators
email: weare@crazyhams.dev
twitter_username:
github_username:  crazyhams
gplus_username:
disqus_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: DX Cluster
    url: /dxcluster
  - title: About Us
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
